import { test } from "node:test";
import assert from "node:assert/strict";
import { writeCaddyfile } from "../src/system.mjs";
import { readFileSync } from "node:fs";
import {
  SUFFIX,
  bareLocalReason,
  expandHost,
  applyHostsLines,
  buildCaddyfile,
  buildHostsLines,
  hostnameWarning,
  normalise,
  urlFor,
  validHostname,
  validPort,
} from "../src/config.mjs";

test("hostnames and ports are validated before they reach a config file", () => {
  for (const h of ["myapp.test", "remoteledger.local", "a.b.c.dev", "my-app.test"]) {
    assert.ok(validHostname(h), h);
  }
  // anything that would need quoting, or is not a hostname at all
  for (const h of ["", "nodots", "-lead.test", "trail-.test", "has space.test", "UPPER OK?.test", "a..b"]) {
    assert.ok(!validHostname(h), `should reject ${JSON.stringify(h)}`);
  }
  for (const p of [1, 80, 5173, 65535]) assert.ok(validPort(p));
  for (const p of [0, -1, 65536, 1.5, "abc", null]) assert.ok(!validPort(p));
});

test("the registry is deduplicated, sorted and stripped of junk", () => {
  const apps = normalise([
    { host: "B.test", port: "3000" },
    { host: "a.test", port: 5173 },
    { host: "b.test", port: 4000 }, // duplicate of B.test, first one wins
    { host: "bad host", port: 1 }, // invalid hostname
    { host: "c.test", port: 0 }, // invalid port
  ]);
  assert.deepEqual(
    apps.map((a) => `${a.host}:${a.port}`),
    ["a.test:5173", "b.test:3000"]
  );
});

test("the Caddyfile forces local certificates", () => {
  const cf = buildCaddyfile([{ host: "myapp.test", port: 3000 }]);
  // Without this, Caddy tries Let's Encrypt for a name it can never validate and
  // fails on every start. It is the single most important line in the file.
  assert.match(cf, /^\s*local_certs\s*$/m);
  assert.match(cf, /^myapp\.test \{$/m);
  assert.match(cf, /reverse_proxy 127\.0\.0\.1:3000/);
  assert.match(cf, /Generated by dropport/);
});

test("an empty registry still produces a valid Caddyfile", () => {
  const cf = buildCaddyfile([]);
  assert.match(cf, /local_certs/);
  assert.match(cf, /No apps registered/);
  assert.ok(!cf.includes("reverse_proxy"));
});

test("hosts edits never touch lines dropport did not write", () => {
  const existing = ["127.0.0.1\tlocalhost", "255.255.255.255\tbroadcasthost", "10.0.0.5\tsomething.i.set.up", ""].join("\n");

  const once = applyHostsLines(existing, [{ host: "a.test", port: 1 }]);
  assert.ok(once.includes("127.0.0.1\tlocalhost"), "system entries survive");
  assert.ok(once.includes("10.0.0.5\tsomething.i.set.up"), "the user's own entries survive");
  assert.ok(once.includes("a.test"));

  // applying repeatedly must not accumulate duplicates
  const twice = applyHostsLines(once, [{ host: "a.test", port: 1 }]);
  assert.equal(twice, once, "idempotent");
  assert.equal((twice.match(/a\.test/g) || []).length, 1);

  // removing an app removes only its line
  const removed = applyHostsLines(twice, []);
  assert.ok(!removed.includes("a.test"));
  assert.ok(removed.includes("10.0.0.5\tsomething.i.set.up"));
  assert.ok(removed.includes("127.0.0.1\tlocalhost"));
});

test("every generated hosts line is tagged so it can be found again", () => {
  const lines = buildHostsLines([{ host: "a.test", port: 1 }, { host: "b.test", port: 2 }]);
  assert.equal(lines.length, 2);
  for (const l of lines) assert.match(l, /^127\.0\.0\.1\t\S+\t# dropport$/);
});

test("risky TLDs are called out rather than silently accepted", () => {
  assert.match(hostnameWarning("app.local") || "", /mDNS|Bonjour/);
  assert.match(hostnameWarning("app.dev") || "", /public TLD/);
  assert.equal(hostnameWarning("app.test"), null, ".test is the reserved one, so no warning");
});

test("urls default to https", () => {
  assert.equal(urlFor({ host: "a.test" }), "https://a.test");
  assert.equal(urlFor({ host: "a.test", tls: false }), "http://a.test");
});

test("a busy port 80 turns off redirects instead of crashing the proxy", () => {
  // Caddy grabs :80 for HTTP->HTTPS redirects even if you never asked for them, and
  // fails to start at all if it cannot. Under launchd KeepAlive that is a silent
  // restart loop, so this must be expressible in the config.
  const normal = buildCaddyfile([{ host: "a.test", port: 1 }]);
  assert.ok(!normal.includes("auto_https"), "no reason to mention it when 80 is free");

  const shared = buildCaddyfile([{ host: "a.test", port: 1 }], { disableRedirects: true });
  assert.match(shared, /auto_https disable_redirects/);
  assert.match(shared, /local_certs/, "still uses the local CA");
  assert.match(shared, /reverse_proxy 127\.0\.0\.1:1/, "still proxies");
});

test("ports can be moved for testing without touching the site blocks", () => {
  const cf = buildCaddyfile([{ host: "a.test", port: 1 }], { httpPort: 8080, httpsPort: 8443 });
  assert.match(cf, /http_port 8080/);
  assert.match(cf, /https_port 8443/);
  assert.match(cf, /^a\.test \{$/m);
});

test("writeCaddyfile forwards its options to the generator", async () => {
  // It silently dropped them once, so the port-80 workaround was computed correctly,
  // announced to the user, and then never written to the file it was meant to change.
  //
  // Writes to an explicit temp path. An earlier version of this test defaulted to
  // ~/.dropport/Caddyfile and overwrote a real machine's config with its fixture.
  const { mkdtempSync } = await import("node:fs");
  const { tmpdir } = await import("node:os");
  const { join } = await import("node:path");
  const target = join(mkdtempSync(join(tmpdir(), "dropport-test-")), "Caddyfile");

  writeCaddyfile([{ host: "a.test", port: 1 }], { disableRedirects: true }, target);
  assert.match(readFileSync(target, "utf8"), /auto_https disable_redirects/);
});

test("a bare name expands under the dropport suffix", () => {
  assert.equal(expandHost("shop"), `shop.${SUFFIX}`);
  assert.equal(expandHost("SHOP"), `shop.${SUFFIX}`, "lowercased");
  assert.equal(expandHost("shop."), `shop.${SUFFIX}`, "a stray trailing dot is not a second label");

  // anything already dotted is taken as given
  assert.equal(expandHost("api.test"), "api.test");
  assert.equal(expandHost("web.dp.local"), "web.dp.local");
  assert.equal(expandHost(""), "");
});

test("bare .local names are refused, deeper ones are not", () => {
  // printer.local is the shape real hardware uses; claiming it starts a fight
  const bare = bareLocalReason("something.local");
  assert.ok(bare, "a single-label .local must be refused");
  assert.equal(bare.label, "something");
  assert.equal(bare.suggestion, `something.${SUFFIX}`);
  assert.match(bare.why, /shared namespace/);

  // already namespaced: nothing else is publishing there
  assert.equal(bareLocalReason(`web.${SUFFIX}`), null, "our own suffix is the recommended form");
  assert.equal(bareLocalReason("a.b.local"), null, "someone else's namespace, but still namespaced");

  // not multicast territory at all
  assert.equal(bareLocalReason("api.test"), null);
  assert.equal(bareLocalReason("shop.localhost"), null);
});

test("the recommended form is not warned about", () => {
  // it suggested x.dp.local, so warning that .local is a bad idea would contradict itself
  assert.equal(hostnameWarning(`shop.${SUFFIX}`), null);
  assert.match(hostnameWarning("shop.local") || "", /mDNS|Bonjour/);
});
