// The pure half of dropport: the registry of hostname -> port, and the Caddyfile it
// generates. No side effects, so it can be tested without touching the machine.
import { homedir } from "node:os";
import { resolve } from "node:path";

export const HOME_DIR = process.env.DROPPORT_HOME || resolve(homedir(), ".dropport");
export const REGISTRY = resolve(HOME_DIR, "apps.json");
export const CADDYFILE = resolve(HOME_DIR, "Caddyfile");
export const HOSTS_MARKER = "# dropport";

/** Hostnames must be safe to put in a Caddyfile and a hosts file without quoting. */
export function validHostname(host) {
  return /^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$/i.test(host || "");
}

export function validPort(port) {
  const n = Number(port);
  return Number.isInteger(n) && n > 0 && n < 65536;
}

/**
 * .local belongs to mDNS/Bonjour (RFC 6762). A hosts entry for it does work, but the
 * resolver consults multicast DNS too, which can add a delay or behave oddly on some
 * networks. .test is reserved for exactly this purpose (RFC 6761) and has no such
 * ambiguity, so we say so once rather than letting someone debug it later.
 */
export function hostnameWarning(host) {
  if (/\.local$/i.test(host)) {
    return `${host} uses .local, which is reserved for mDNS/Bonjour. It normally works via the hosts file, but .test is the TLD reserved for local development and avoids the ambiguity entirely.`;
  }
  if (/\.(dev|app|zip|mov)$/i.test(host)) {
    return `${host} uses a real public TLD with browser-enforced HTTPS. It will work locally, but you are shadowing a name someone else owns.`;
  }
  return null;
}

export function normalise(apps) {
  const out = [];
  const seen = new Set();
  for (const a of apps || []) {
    const host = String(a.host || "").toLowerCase().trim();
    if (!validHostname(host) || !validPort(a.port) || seen.has(host)) continue;
    seen.add(host);
    out.push({ host, port: Number(a.port), tls: a.tls !== false, note: a.note || null });
  }
  return out.sort((a, b) => a.host.localeCompare(b.host));
}

/**
 * Build the Caddyfile.
 *
 * local_certs is the load-bearing line: without it Caddy tries to get a public
 * certificate from Let's Encrypt for names like remoteledger.local, which cannot work
 * and would fail on every start. It forces Caddy's own local CA instead, which is what
 * makes https work with a real padlock once that CA is trusted.
 */
export function buildCaddyfile(apps, opts = {}) {
  const list = normalise(apps);
  const header = [
    "# Generated by dropport. Edits here are overwritten — change the registry instead:",
    "#   dropport add <host> <port>",
    "",
    "{",
    "\tlocal_certs",
    opts.adminOff ? "\tadmin off" : `\tadmin ${opts.admin || "localhost:2019"}`,
    "}",
    "",
  ];
  if (!list.length) {
    return header.concat(["# No apps registered yet.", ""]).join("\n");
  }
  const blocks = list.map((a) => {
    const lines = [`${a.host} {`];
    if (a.note) lines.push(`\t# ${a.note.replace(/\n/g, " ")}`);
    if (!a.tls) lines.push("\ttls internal"); // explicit even when it is the default
    lines.push(`\treverse_proxy 127.0.0.1:${a.port}`);
    lines.push("}");
    return lines.join("\n");
  });
  return header.concat(blocks).join("\n") + "\n";
}

/** The lines dropport owns in the hosts file, one per app. */
export function buildHostsLines(apps) {
  return normalise(apps).map((a) => `127.0.0.1\t${a.host}\t${HOSTS_MARKER}`);
}

/**
 * Rewrite a hosts file so it contains exactly our lines and nothing else of ours.
 * Every line we did not add is preserved untouched — this file is shared with the
 * system and with whatever else the user has put in it.
 */
export function applyHostsLines(existing, apps) {
  const keep = String(existing || "")
    .split(/\r?\n/)
    .filter((l) => !l.includes(HOSTS_MARKER));
  while (keep.length && keep[keep.length - 1].trim() === "") keep.pop();
  const ours = buildHostsLines(apps);
  return (ours.length ? [...keep, "", ...ours, ""] : [...keep, ""]).join("\n");
}

export function urlFor(app) {
  return `${app.tls === false ? "http" : "https"}://${app.host}`;
}
